---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: express
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleUp:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 60  # Réduit de 300s (défaut) à 60s pour tests
      policies:
      - type: Percent
        value: 50  # Scale down de 50% au lieu de 10% pour aller plus vite
        periodSeconds: 60
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
